package HMS;

public class Patient {
    private int id;
    private int doctor_id;
    private String name;
    private int age;  // Age remains as an integer for database compatibility
    private String disease;
    private String treatment;
    private String prescription;

    // Constructor
    public Patient(int id, int doctor_id, String name, int age, String disease, String treatment, String prescription) {
        this.id = id;
        this.doctor_id = doctor_id;
        this.name = name;
        this.age = age;
        this.disease = disease;
        this.treatment = treatment;
        this.prescription = prescription;
    }

    // Constructor overload (for new patients without an ID)
    public Patient(int doctor_id, String name, int age, String disease, String treatment, String prescription) {
        this.id = 0;  // ID will be auto-generated by the database
        this.doctor_id = doctor_id;
        this.name = name;
        this.age = age;
        this.disease = disease;
        this.treatment = treatment;
        this.prescription = prescription;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getDoctorId() {
        return doctor_id;
    }

    public void setDoctorId(int doctor_id) {
        this.doctor_id = doctor_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;  // Return age as an integer
    }

    public void setAge(int age) {
        this.age = age;  // Set age as an integer
    }

    public String getDisease() {
        return disease;
    }

    public void setDisease(String disease) {
        this.disease = disease;
    }

    public String getTreatment() {
        return treatment;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getPrescription() {
        return prescription;
    }

    public void setPrescription(String prescription) {
        this.prescription = prescription;
    }

    // Optional: Method to validate and convert the age input
    public static int validateAndConvertAge(String ageStr) {
        try {
            return Integer.parseInt(ageStr);  // Convert string to int
        } catch (NumberFormatException e) {
            // If invalid age, return -1 (or handle it according to your requirements)
            return -1;
        }
    }
}
